version: '3.9'
services:
  web:
    build: .
    ports:
      - "7001:7001"
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "./db:/docker-entrypoint-initdb.d/"
  redis:
    image: redis
    container_name: redis
    restart: always
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf